url: https://open-policy-agent.github.io/gatekeeper/charts/gatekeeper-3.11.0.tgz
version: 102.1.0
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: crd-manifest
      addCRDValidationToMainChart: true
